# Generated by Django 4.2.6 on 2025-02-26 06:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('city', '0002_city_user_country_user_province_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='province',
            options={'ordering': ('name',), 'verbose_name_plural': 'Tỉnh, khu vực'},
        ),
        migrations.AlterField(
            model_name='province',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provinces', to=settings.AUTH_USER_MODEL),
        ),
    ]
