# Generated by Django 4.2.6 on 2025-02-26 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0003_alter_province_options_alter_province_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='province',
            unique_together={('slug', 'country')},
        ),
    ]
