# Generated by Django 4.2.6 on 2025-02-26 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0007_alter_province_unique_together_alter_province_slug_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='province',
            name='unique_slug_country',
        ),
        migrations.AlterField(
            model_name='province',
            name='slug',
            field=models.SlugField(max_length=127, unique=True),
        ),
    ]
