# Generated by Django 4.2.6 on 2025-02-26 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0008_remove_province_unique_slug_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='province',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='province_country', to='city.country', verbose_name='Quốc gia'),
        ),
    ]
