# Generated by Django 4.2.6 on 2025-02-26 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0009_alter_province_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='province',
            name='user',
        ),
        migrations.AlterField(
            model_name='province',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provinces', to='city.country'),
        ),
    ]
