# Generated by Django 4.2.6 on 2025-02-26 07:46

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0011_remove_province_country_province_countries_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='province',
            name='countries',
        ),
        migrations.AddField(
            model_name='province',
            name='country',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='quoc_gia', chained_model_field='quoc_gia', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='country_id', to='city.country', verbose_name='Quốc gia'),
            preserve_default=False,
        ),
    ]
