# Generated by Django 4.2.6 on 2025-02-26 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0012_remove_province_countries_province_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='province',
            name='country',
        ),
        migrations.RemoveField(
            model_name='province',
            name='user',
        ),
    ]
