# Generated by Django 4.2.6 on 2025-02-26 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0004_alter_work_province'),
        ('city', '0013_remove_province_country_remove_province_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Province',
        ),
    ]
