# Generated by Django 4.2.6 on 2025-02-26 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0015_province'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='province',
            name='slug',
        ),
    ]
