# Generated by Django 4.2.6 on 2025-02-26 09:14

from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0018_alter_province_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='show_home',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='country',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='country'),
        ),
    ]
