# Generated by Django 4.2.6 on 2025-02-26 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0019_country_show_home_alter_country_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='province',
            old_name='quoc_gia',
            new_name='country',
        ),
    ]
