# Generated by Django 4.2.6 on 2025-02-28 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0020_rename_quoc_gia_province_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='meta_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
