# Generated by Django 4.2.6 on 2025-03-03 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0022_alter_city_slug_alter_country_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='user',
        ),
        migrations.RemoveField(
            model_name='country',
            name='user',
        ),
        migrations.RemoveField(
            model_name='province',
            name='user',
        ),
    ]
