# Generated by Django 4.2.6 on 2025-03-04 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0023_remove_city_user_remove_country_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='province',
            options={'verbose_name_plural': 'Tỉnh, khu vực'},
        ),
    ]
