# Generated by Django 4.2.6 on 2025-03-04 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0024_alter_province_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ('priority',), 'verbose_name_plural': 'Nơi thi tuyển'},
        ),
    ]
