# Generated by Django 4.2.6 on 2025-03-03 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_alter_page_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='user',
        ),
    ]
