# Generated by Django 5.0.6 on 2025-02-19 16:11

import ckeditor_uploader.fields
import datetime
import django.db.models.deletion
import smart_selects.db_fields
import sorl.thumbnail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('city', '0001_initial'),
        ('profession', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Giới tính',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Workmanship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Tay Nghề',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Tên đơn hàng')),
                ('slug', models.SlugField(max_length=127, unique=True)),
                ('tu_van', models.CharField(max_length=250, verbose_name='Tư vấn')),
                ('phone', models.CharField(max_length=250, verbose_name='Số điện thoại')),
                ('link_zalo', models.CharField(blank=True, max_length=250, null=True)),
                ('link_facebook', models.CharField(blank=True, max_length=250, null=True)),
                ('ma_don_hang', models.PositiveIntegerField(default=0, verbose_name='Mã đơn hàng')),
                ('cong_ty_nghiep_doan', models.CharField(blank=True, max_length=250, null=True, verbose_name='Công ty, nghiệp đoàn')),
                ('cong_viec_cu_the', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Công việc cụ thể')),
                ('thoi_gian_lam_viec', models.CharField(max_length=250, verbose_name='Thời gian làm việc')),
                ('luong_co_ban', models.CharField(max_length=250, verbose_name='Lương cơ bản')),
                ('luong_co_ban_menh_gia', models.CharField(choices=[('0', 'Triệu'), ('1', 'Yên'), ('2', 'Man'), ('3', 'Đài Tệ'), ('4', 'Usd'), ('5', 'Euro'), ('6', 'Đô Sing'), ('7', 'Aud'), ('8', 'Bgn'), ('9', 'Cad'), ('10', 'Cny'), ('11', 'Bảng Anh'), ('12', 'Hkd'), ('13', 'Huf'), ('14', 'Myr'), ('15', 'Nzd'), ('16', 'Pln'), ('17', 'Leu'), ('18', 'Rub'), ('19', 'Sar'), ('20', 'Won')], default=0, verbose_name='Mệnh giá lương cơ bản')),
                ('lam_them', models.CharField(max_length=250, verbose_name='Làm thêm')),
                ('thu_nhap_du_kien', models.CharField(max_length=250, verbose_name='Thu nhập dự kiến')),
                ('thu_nhap_du_kien_menh_gia', models.CharField(choices=[('0', 'Triệu'), ('1', 'Yên'), ('2', 'Man'), ('3', 'Đài Tệ'), ('4', 'Usd'), ('5', 'Euro'), ('6', 'Đô Sing'), ('7', 'Aud'), ('8', 'Bgn'), ('9', 'Cad'), ('10', 'Cny'), ('11', 'Bảng Anh'), ('12', 'Hkd'), ('13', 'Huf'), ('14', 'Myr'), ('15', 'Nzd'), ('16', 'Pln'), ('17', 'Leu'), ('18', 'Rub'), ('19', 'Sar'), ('20', 'Won')], default=0, verbose_name='Mệnh giá thu nhập dự kiến')),
                ('quyen_loi_khac', models.TextField(blank=True, null=True, verbose_name='Quyền lợi khác')),
                ('so_luong_tuyen', models.CharField(default=0, verbose_name='Số lượng tuyển')),
                ('hop_dong', models.CharField(choices=[('0', 'Không giới hạn'), ('1', '01 năm'), ('2', '02 năm'), ('3', '03 năm'), ('4', '04 năm'), ('5', '05 năm'), ('6', '06 năm'), ('7', '07 năm'), ('8', '08 năm'), ('9', '09 năm'), ('10', '10 năm')], default=0, verbose_name='Hợp đồng')),
                ('phi_xuat_canh', models.CharField(default=0, verbose_name='Phí xuất cảnh')),
                ('phi_xuat_canh_menh_gia', models.CharField(choices=[('0', 'Triệu'), ('1', 'Yên'), ('2', 'Man'), ('3', 'Đài Tệ'), ('4', 'Usd'), ('5', 'Euro'), ('6', 'Đô Sing'), ('7', 'Aud'), ('8', 'Bgn'), ('9', 'Cad'), ('10', 'Cny'), ('11', 'Bảng Anh'), ('12', 'Hkd'), ('13', 'Huf'), ('14', 'Myr'), ('15', 'Nzd'), ('16', 'Pln'), ('17', 'Leu'), ('18', 'Rub'), ('19', 'Sar'), ('20', 'Won')], default=0, verbose_name='Phí xuất cảnh mệnh giá')),
                ('chuong_trinh_ho_tro', models.TextField(blank=True, null=True, verbose_name='Chương trình hỗ trợ')),
                ('image', sorl.thumbnail.fields.ImageField(upload_to='work', verbose_name='Ảnh')),
                ('noi_dung_chi_tiet', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Nội dung chi tiết')),
                ('nam_sinh', models.CharField(default=0, verbose_name='Năm sinh bắt đầu')),
                ('ket_thuc_nam_sinh', models.CharField(default=0, verbose_name='Năm sinh kết thúc')),
                ('trinh_do_hoc_van', models.CharField(choices=[('0', 'Không yêu cầu'), ('1', 'Tốt nghiệp cấp 2 trở lên'), ('2', 'Bằng nghề trở lên'), ('3', 'Tốt nghiệp cao đẳng trở lên'), ('4', 'Tốt nghiệp đại học trở lên')], default=0, verbose_name='Trình độ học vấn')),
                ('chuyen_nganh', models.CharField(choices=[('0', 'Không yêu cầu'), ('1', 'Các ngành kinh tế'), ('2', 'Các ngành nghề khác'), ('3', 'Các ngành về y dược'), ('4', 'Cơ khí, cơ điện tử'), ('5', 'Công nghệ thông tin, phần mềm'), ('6', 'Dệt may'), ('7', 'Điện tử, điện lạnh, tự động hóa'), ('8', 'Nhà hàng, khách sạn, du lịch'), ('9', 'Nông nghiệp, lâm nghiệp, chăn nuôi, thú y'), ('10', 'Sinh học, thực phẩm, thủy sản'), ('11', 'Viễn thông, truyền thông'), ('12', 'Xây dựng, kiến trúc, địa chất')], default=0, verbose_name='Chuyên ngành')),
                ('ngoai_ngu', models.CharField(choices=[('0', 'Không yêu cầu'), ('1', 'Tiếng Nhật'), ('2', 'Tiếng Trung'), ('3', 'Tiếng Anh'), ('4', 'Tiếng Hàn'), ('5', 'Ngoại ngữ khác')], default=0, verbose_name='Ngoại ngữ')),
                ('yeu_cau_hoc_tieng', models.CharField(choices=[('0', 'Không yêu cầu'), ('1', '01 tháng'), ('2', '02 tháng'), ('3', '03 tháng'), ('4', '04 tháng'), ('5', '05 tháng'), ('6', '06 tháng')], default=0, verbose_name='Yêu cầu tiếng anh')),
                ('tinh_trang_suc_khoe', models.CharField(choices=[('0', 'Không yêu cầu'), ('1', 'Tốt')], default=0, verbose_name='Tình trạng sức khoẻ')),
                ('thi_luc', models.CharField(choices=[('0', 'Tốt'), ('1', 'Nhận cận thị'), ('2', 'Không nhận cận thị')], default=0, verbose_name='Thị lực')),
                ('viem_gan_b', models.CharField(choices=[('0', 'Không yêu cầu'), ('1', 'Nhận VGB'), ('2', 'Không nhận VGB')], default=0, verbose_name='VGB')),
                ('xam_hinh', models.CharField(choices=[('0', 'Không yêu cầu'), ('1', 'Có nhận'), ('2', 'Không nhận')], default=0, verbose_name='Xăm hình')),
                ('yeu_cau_khac', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Yêu cầu khác')),
                ('hinh_thuc_thi_tuyen', models.CharField(max_length=250, verbose_name='Hình thức thi tuyển')),
                ('ngay_thi_tuyen', models.DateField(default=datetime.date.today, verbose_name='Ngày thi tuyển')),
                ('han_dang_ky', models.DateField(default=datetime.date.today, verbose_name='Hạn đăng ký')),
                ('du_kien_xuat_canh', models.DateField(choices=[(datetime.date(2025, 2, 1), '02/2025'), (datetime.date(2025, 3, 1), '03/2025'), (datetime.date(2025, 4, 1), '04/2025'), (datetime.date(2025, 5, 1), '05/2025'), (datetime.date(2025, 6, 1), '06/2025'), (datetime.date(2025, 7, 1), '07/2025'), (datetime.date(2025, 8, 1), '08/2025'), (datetime.date(2025, 9, 1), '09/2025'), (datetime.date(2025, 10, 1), '10/2025'), (datetime.date(2025, 11, 1), '11/2025'), (datetime.date(2025, 12, 1), '12/2025'), (datetime.date(2026, 1, 1), '01/2026'), (datetime.date(2026, 2, 1), '02/2026'), (datetime.date(2026, 3, 1), '03/2026'), (datetime.date(2026, 4, 1), '04/2026'), (datetime.date(2026, 5, 1), '05/2026'), (datetime.date(2026, 6, 1), '06/2026'), (datetime.date(2026, 7, 1), '07/2026'), (datetime.date(2026, 8, 1), '08/2026'), (datetime.date(2026, 9, 1), '09/2026'), (datetime.date(2026, 10, 1), '10/2026'), (datetime.date(2026, 11, 1), '11/2026'), (datetime.date(2026, 12, 1), '12/2026'), (datetime.date(2027, 1, 1), '01/2027'), (datetime.date(2027, 2, 1), '02/2027'), (datetime.date(2027, 3, 1), '03/2027'), (datetime.date(2027, 4, 1), '04/2027'), (datetime.date(2027, 5, 1), '05/2027'), (datetime.date(2027, 6, 1), '06/2027'), (datetime.date(2027, 7, 1), '07/2027'), (datetime.date(2027, 8, 1), '08/2027'), (datetime.date(2027, 9, 1), '09/2027'), (datetime.date(2027, 10, 1), '10/2027'), (datetime.date(2027, 11, 1), '11/2027'), (datetime.date(2027, 12, 1), '12/2027'), (datetime.date(2028, 1, 1), '01/2028'), (datetime.date(2028, 2, 1), '02/2028'), (datetime.date(2028, 3, 1), '03/2028'), (datetime.date(2028, 4, 1), '04/2028'), (datetime.date(2028, 5, 1), '05/2028'), (datetime.date(2028, 6, 1), '06/2028'), (datetime.date(2028, 7, 1), '07/2028'), (datetime.date(2028, 8, 1), '08/2028'), (datetime.date(2028, 9, 1), '09/2028'), (datetime.date(2028, 10, 1), '10/2028'), (datetime.date(2028, 11, 1), '11/2028'), (datetime.date(2028, 12, 1), '12/2028')], default=datetime.date.today, verbose_name='Dự kiến xuất cảnh')),
                ('priority', models.IntegerField(default=1)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_country', to='city.country', verbose_name='Quốc gia')),
                ('gioi_tinh', models.ManyToManyField(related_name='require_gioi_tinh', to='work.gender', verbose_name='Giới tính')),
                ('nganh_nghe', models.ManyToManyField(related_name='work_nganh_nghe', to='profession.profession', verbose_name='Ngành nghề')),
                ('noi_thi_tuyen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='city.city', verbose_name='Nơi thi tuyển')),
                ('province', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='quoc_gia', chained_model_field='quoc_gia', on_delete=django.db.models.deletion.CASCADE, related_name='country_id', to='city.province', verbose_name='Tỉnh, khu vực')),
                ('tay_nghe', models.ManyToManyField(related_name='require_tay_nghe', to='work.workmanship', verbose_name='Tay Nghề')),
            ],
            options={
                'verbose_name_plural': 'Việc làm',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', sorl.thumbnail.fields.ImageField(upload_to='work')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_work', to='work.work')),
            ],
            options={
                'verbose_name_plural': 'Images',
                'ordering': ('id',),
            },
        ),
    ]
