# Generated by Django 4.2.6 on 2025-02-24 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='hot',
            field=models.BooleanField(default=False, verbose_name='Việc làm đang hot'),
        ),
        migrations.AddField(
            model_name='work',
            name='view',
            field=models.PositiveIntegerField(default=0, verbose_name='Lượt xem'),
        ),
    ]
