# Generated by Django 4.2.6 on 2025-02-26 07:50

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('profession', '0003_province'),
        ('work', '0003_gender_user_image_user_work_user_workmanship_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='province',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='quoc_gia', chained_model_field='quoc_gia', on_delete=django.db.models.deletion.CASCADE, related_name='country_id', to='profession.province', verbose_name='Tỉnh, khu vực'),
        ),
    ]
