# Generated by Django 4.2.6 on 2025-02-26 07:52

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0015_province'),
        ('work', '0004_alter_work_province'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='province',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='quoc_gia', chained_model_field='quoc_gia', on_delete=django.db.models.deletion.CASCADE, related_name='country_id', to='city.province', verbose_name='Tỉnh, khu vực'),
        ),
    ]
