# Generated by Django 4.2.6 on 2025-02-26 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0005_alter_work_province'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='han_dang_ky',
            field=models.DateField(default='0000-00-00', verbose_name='Hạn đăng ký'),
        ),
        migrations.AlterField(
            model_name='work',
            name='ngay_thi_tuyen',
            field=models.DateField(default='0000-00-00', verbose_name='Ngày thi tuyển'),
        ),
    ]
