# Generated by Django 4.2.6 on 2025-02-26 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0019_country_show_home_alter_country_image'),
        ('work', '0008_alter_work_province'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_country', to='city.country'),
        ),
    ]
