# Generated by Django 4.2.6 on 2025-02-26 12:01

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0019_country_show_home_alter_country_image'),
        ('work', '0009_alter_work_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_country', to='city.country', verbose_name='Quốc gia'),
        ),
        migrations.AlterField(
            model_name='work',
            name='province',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='work_country', chained_model_field='work_country', on_delete=django.db.models.deletion.CASCADE, related_name='work_id', to='city.province', verbose_name='Tỉnh, khu vực'),
        ),
    ]
