# Generated by Django 4.2.6 on 2025-02-26 12:17

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0020_rename_quoc_gia_province_country'),
        ('work', '0016_rename_quoc_gia_work_country_alter_work_province'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_country', to='city.country', verbose_name='Quốc gia'),
        ),
        migrations.AlterField(
            model_name='work',
            name='province',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='country', chained_model_field='country', on_delete=django.db.models.deletion.CASCADE, related_name='work_id', to='city.province', verbose_name='Tỉnh, khu vực'),
        ),
    ]
