# Generated by Django 4.2.6 on 2025-02-26 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0020_remove_work_phone_remove_work_tu_van_alter_work_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='lam_them',
            field=models.CharField(choices=[('0', 'Làm thêm nhiều'), ('1', 'Làm thêm 1 - 2 h/ngày'), ('2', 'Làm thêm 2 - 3 h/ngày'), ('3', 'Làm thêm 2 - 4 h/ngày'), ('4', 'Làm thêm 3 - 5 h/ngày'), ('5', 'Làm thêm 4 - 6 h/ngày'), ('6', 'Làm thêm trung bình'), ('7', 'Không có làm thêm')], default=0, verbose_name='Làm thêm'),
        ),
    ]
