# Generated by Django 4.2.6 on 2025-02-26 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0021_alter_work_lam_them'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='tay_nghe',
            field=models.ManyToManyField(blank=True, null=True, related_name='require_tay_nghe', to='work.workmanship', verbose_name='Tay Nghề'),
        ),
    ]
