# Generated by Django 4.2.6 on 2025-02-26 13:00

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0022_alter_work_tay_nghe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='quyen_loi_khac',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Quyền lợi khác'),
        ),
    ]
