# Generated by Django 4.2.6 on 2025-02-26 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0024_alter_work_han_dang_ky_alter_work_ngay_thi_tuyen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='han_dang_ky',
            field=models.DateField(blank=True, null=True, verbose_name='Hạn đăng ký'),
        ),
        migrations.AlterField(
            model_name='work',
            name='ngay_thi_tuyen',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày thi tuyển'),
        ),
    ]
