# Generated by Django 4.2.6 on 2025-02-26 13:50

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0025_alter_work_han_dang_ky_alter_work_ngay_thi_tuyen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='link_facebook',
        ),
        migrations.RemoveField(
            model_name='work',
            name='link_zalo',
        ),
        migrations.AlterField(
            model_name='work',
            name='chuong_trinh_ho_tro',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Chương trình hỗ trợ'),
        ),
    ]
