# Generated by Django 4.2.6 on 2025-02-26 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0026_remove_work_link_facebook_remove_work_link_zalo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='work',
            options={'ordering': ('id',), 'verbose_name_plural': 'Việc làm'},
        ),
    ]
