# Generated by Django 4.2.6 on 2025-02-26 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0027_alter_work_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='work',
            options={'ordering': ('-id',), 'verbose_name_plural': 'Việc làm'},
        ),
    ]
