# Generated by Django 4.2.6 on 2025-02-27 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0028_alter_work_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='chuyen_nganh',
            field=models.CharField(blank=True, choices=[('Không yêu cầu', 'Không yêu cầu'), ('Các ngành kinh tế', 'Các ngành kinh tế'), ('Các ngành nghề khác', 'Các ngành nghề khác'), ('Các ngành về y dược', 'Các ngành về y dược'), ('Cơ khí, cơ điện tử', 'Cơ khí, cơ điện tử'), ('Công nghệ thông tin, phần mềm', 'Công nghệ thông tin, phần mềm'), ('Dệt may', 'Dệt may'), ('Điện tử, điện lạnh, tự động hóa', 'Điện tử, điện lạnh, tự động hóa'), ('Nhà hàng, khách sạn, du lịch', 'Nhà hàng, khách sạn, du lịch'), ('Nông nghiệp, lâm nghiệp, chăn nuôi, thú y', 'Nông nghiệp, lâm nghiệp, chăn nuôi, thú y'), ('Sinh học, thực phẩm, thủy sản', 'Sinh học, thực phẩm, thủy sản'), ('Viễn thông, truyền thông', 'Viễn thông, truyền thông'), ('Xây dựng, kiến trúc, địa chất', 'Xây dựng, kiến trúc, địa chất')], null=True, verbose_name='Chuyên ngành'),
        ),
        migrations.AlterField(
            model_name='work',
            name='hop_dong',
            field=models.CharField(blank=True, choices=[('Không giới hạn', 'Không giới hạn'), ('01 năm', '01 năm'), ('02 năm', '02 năm'), ('03 năm', '03 năm'), ('04 năm', '04 năm'), ('05 năm', '05 năm'), ('06 năm', '06 năm'), ('07 năm', '07 năm'), ('08 năm', '08 năm'), ('09 năm', '09 năm'), ('10 năm', '10 năm')], null=True, verbose_name='Hợp đồng'),
        ),
        migrations.AlterField(
            model_name='work',
            name='lam_them',
            field=models.CharField(blank=True, choices=[('Làm thêm nhiều', 'Làm thêm nhiều'), ('Làm thêm 1 - 2 h/ngày', 'Làm thêm 1 - 2 h/ngày'), ('Làm thêm 2 - 3 h/ngày', 'Làm thêm 2 - 3 h/ngày'), ('Làm thêm 2 - 4 h/ngày', 'Làm thêm 2 - 4 h/ngày'), ('Làm thêm 3 - 5 h/ngày', 'Làm thêm 3 - 5 h/ngày'), ('Làm thêm 4 - 6 h/ngày', 'Làm thêm 4 - 6 h/ngày'), ('Làm thêm trung bình', 'Làm thêm trung bình'), ('Không có làm thêm', 'Không có làm thêm')], null=True, verbose_name='Làm thêm'),
        ),
        migrations.AlterField(
            model_name='work',
            name='luong_co_ban_menh_gia',
            field=models.CharField(blank=True, choices=[('Triệu', 'Triệu'), ('Yên', 'Yên'), ('Man', 'Man'), ('Đài Tệ', 'Đài Tệ'), ('Usd', 'Usd'), ('Euro', 'Euro'), ('Đô Sing', 'Đô Sing'), ('Aud', 'Aud'), ('Bgn', 'Bgn'), ('Cad', 'Cad'), ('Cny', 'Cny'), ('Bảng Anh', 'Bảng Anh'), ('Hkd', 'Hkd'), ('Huf', 'Huf'), ('Myr', 'Myr'), ('Nzd', 'Nzd'), ('Pln', 'Pln'), ('Leu', 'Leu'), ('Rub', 'Rub'), ('Sar', 'Sar'), ('Won', 'Won')], null=True, verbose_name='Mệnh giá lương cơ bản'),
        ),
        migrations.AlterField(
            model_name='work',
            name='ngoai_ngu',
            field=models.CharField(blank=True, choices=[('Không yêu cầu', 'Không yêu cầu'), ('Tiếng Nhật', 'Tiếng Nhật'), ('Tiếng Trung', 'Tiếng Trung'), ('Tiếng Anh', 'Tiếng Anh'), ('Tiếng Hàn', 'Tiếng Hàn'), ('Ngoại ngữ khác', 'Ngoại ngữ khác')], null=True, verbose_name='Ngoại ngữ'),
        ),
        migrations.AlterField(
            model_name='work',
            name='phi_xuat_canh_menh_gia',
            field=models.CharField(blank=True, choices=[('Triệu', 'Triệu'), ('Yên', 'Yên'), ('Man', 'Man'), ('Đài Tệ', 'Đài Tệ'), ('Usd', 'Usd'), ('Euro', 'Euro'), ('Đô Sing', 'Đô Sing'), ('Aud', 'Aud'), ('Bgn', 'Bgn'), ('Cad', 'Cad'), ('Cny', 'Cny'), ('Bảng Anh', 'Bảng Anh'), ('Hkd', 'Hkd'), ('Huf', 'Huf'), ('Myr', 'Myr'), ('Nzd', 'Nzd'), ('Pln', 'Pln'), ('Leu', 'Leu'), ('Rub', 'Rub'), ('Sar', 'Sar'), ('Won', 'Won')], null=True, verbose_name='Phí xuất cảnh mệnh giá'),
        ),
        migrations.AlterField(
            model_name='work',
            name='thi_luc',
            field=models.CharField(blank=True, choices=[('Tốt', 'Tốt'), ('Nhận cận thị', 'Nhận cận thị'), ('Không nhận cận thị', 'Không nhận cận thị')], null=True, verbose_name='Thị lực'),
        ),
        migrations.AlterField(
            model_name='work',
            name='thu_nhap_du_kien_menh_gia',
            field=models.CharField(blank=True, choices=[('Triệu', 'Triệu'), ('Yên', 'Yên'), ('Man', 'Man'), ('Đài Tệ', 'Đài Tệ'), ('Usd', 'Usd'), ('Euro', 'Euro'), ('Đô Sing', 'Đô Sing'), ('Aud', 'Aud'), ('Bgn', 'Bgn'), ('Cad', 'Cad'), ('Cny', 'Cny'), ('Bảng Anh', 'Bảng Anh'), ('Hkd', 'Hkd'), ('Huf', 'Huf'), ('Myr', 'Myr'), ('Nzd', 'Nzd'), ('Pln', 'Pln'), ('Leu', 'Leu'), ('Rub', 'Rub'), ('Sar', 'Sar'), ('Won', 'Won')], null=True, verbose_name='Mệnh giá thu nhập dự kiến'),
        ),
        migrations.AlterField(
            model_name='work',
            name='tinh_trang_suc_khoe',
            field=models.CharField(blank=True, choices=[('Không yêu cầu', 'Không yêu cầu'), ('Tốt', 'Tốt')], null=True, verbose_name='Tình trạng sức khoẻ'),
        ),
        migrations.AlterField(
            model_name='work',
            name='trinh_do_hoc_van',
            field=models.CharField(blank=True, choices=[('Không yêu cầu', 'Không yêu cầu'), ('Tốt nghiệp cấp 2 trở lên', 'Tốt nghiệp cấp 2 trở lên'), ('Bằng nghề trở lên', 'Bằng nghề trở lên'), ('Tốt nghiệp cao đẳng trở lên', 'Tốt nghiệp cao đẳng trở lên'), ('Tốt nghiệp đại học trở lên', 'Tốt nghiệp đại học trở lên')], null=True, verbose_name='Trình độ học vấn'),
        ),
        migrations.AlterField(
            model_name='work',
            name='viem_gan_b',
            field=models.CharField(blank=True, choices=[('Không yêu cầu', 'Không yêu cầu'), ('Nhận VGB', 'Nhận VGB'), ('Không nhận VGB', 'Không nhận VGB')], null=True, verbose_name='VGB'),
        ),
        migrations.AlterField(
            model_name='work',
            name='xam_hinh',
            field=models.CharField(blank=True, choices=[('Không yêu cầu', 'Không yêu cầu'), ('Có nhận', 'Có nhận'), ('Không nhận', 'Không nhận')], null=True, verbose_name='Xăm hình'),
        ),
        migrations.AlterField(
            model_name='work',
            name='yeu_cau_hoc_tieng',
            field=models.CharField(blank=True, choices=[('Không yêu cầu', 'Không yêu cầu'), ('01 tháng', '01 tháng'), ('02 tháng', '02 tháng'), ('03 tháng', '03 tháng'), ('04 tháng', '04 tháng'), ('05 tháng', '05 tháng'), ('06 tháng', '06 tháng')], null=True, verbose_name='Yêu cầu tiếng anh'),
        ),
    ]
