# Generated by Django 4.2.6 on 2025-03-01 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0031_alter_work_du_kien_xuat_canh'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='work',
            options={'ordering': ('-id',), 'verbose_name_plural': 'Đơn hàng'},
        ),
    ]
