# Generated by Django 4.2.6 on 2025-03-03 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0032_alter_work_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='ngoai_ngu',
            field=models.CharField(blank=True, choices=[('Không', 'Không'), ('Tiếng Nhật', 'Tiếng Nhật'), ('Tiếng Trung', 'Tiếng Trung'), ('Tiếng Anh', 'Tiếng Anh'), ('Tiếng Hàn', 'Tiếng Hàn'), ('Ngoại ngữ khác', 'Ngoại ngữ khác')], null=True, verbose_name='Ngoại ngữ'),
        ),
        migrations.AlterField(
            model_name='work',
            name='trinh_do_hoc_van',
            field=models.CharField(blank=True, choices=[('Không', 'Không'), ('Tốt nghiệp cấp 2 trở lên', 'Tốt nghiệp cấp 2 trở lên'), ('Bằng nghề trở lên', 'Bằng nghề trở lên'), ('Tốt nghiệp cao đẳng trở lên', 'Tốt nghiệp cao đẳng trở lên'), ('Tốt nghiệp đại học trở lên', 'Tốt nghiệp đại học trở lên')], null=True, verbose_name='Trình độ học vấn'),
        ),
    ]
