# Generated by Django 4.2.6 on 2025-03-03 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0033_alter_work_ngoai_ngu_alter_work_trinh_do_hoc_van'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gender',
            name='user',
        ),
        migrations.RemoveField(
            model_name='image',
            name='user',
        ),
        migrations.RemoveField(
            model_name='workmanship',
            name='user',
        ),
    ]
