# Generated by Django 4.2.6 on 2025-03-04 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0034_remove_gender_user_remove_image_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='trinh_do_hoc_van',
            field=models.CharField(blank=True, choices=[('Không', 'Không'), ('Tốt nghiệp cấp 2 trở lê', 'Tốt nghiệp cấp 2 trở lên'), ('Tốt nghiệp cấp 3 trở lên', 'Tốt nghiệp cấp 3 trở lên'), ('Bằng nghề trở lên', 'Bằng nghề trở lên'), ('Tốt nghiệp cao đẳng trở lên', 'Tốt nghiệp cao đẳng trở lên'), ('Tốt nghiệp đại học trở lên', 'Tốt nghiệp đại học trở lên')], null=True, verbose_name='Trình độ học vấn'),
        ),
    ]
