# Generated by Django 4.2.6 on 2025-03-04 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0026_alter_city_options_alter_province_options'),
        ('work', '0036_alter_work_du_kien_xuat_canh_alter_work_han_dang_ky_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='noi_thi_tuyen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='city.city', verbose_name='Nơi thi tuyển'),
        ),
    ]
