# Generated by Django 4.2.6 on 2025-03-04 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profession', '0006_remove_profession_user'),
        ('work', '0037_alter_work_noi_thi_tuyen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='gioi_tinh',
            field=models.ManyToManyField(blank=True, null=True, related_name='require_gioi_tinh', to='work.gender', verbose_name='Giới tính'),
        ),
        migrations.AlterField(
            model_name='work',
            name='nganh_nghe',
            field=models.ManyToManyField(blank=True, null=True, related_name='work_nganh_nghe', to='profession.profession', verbose_name='Ngành nghề'),
        ),
    ]
