# Generated by Django 4.2.6 on 2025-03-04 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0038_alter_work_gioi_tinh_alter_work_nganh_nghe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='han_dang_ky',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Hạn đăng ký'),
        ),
    ]
