# Generated by Django 4.2.6 on 2025-03-04 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0039_alter_work_han_dang_ky'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
