# Generated by Django 4.2.6 on 2025-03-04 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0026_alter_city_options_alter_province_options'),
        ('work', '0040_work_is_confirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='noi_thi_tuyen',
        ),
        migrations.AddField(
            model_name='work',
            name='noi_thi_tuyen',
            field=models.ManyToManyField(blank=True, null=True, to='city.city', verbose_name='Nơi thi tuyển'),
        ),
    ]
