# Generated by Django 4.2.6 on 2025-03-04 16:20

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0041_remove_work_noi_thi_tuyen_work_noi_thi_tuyen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='work', verbose_name='Ảnh'),
        ),
    ]
