# Generated by Django 4.2.6 on 2025-03-05 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0042_alter_work_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='hot_expiry',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ngày hết hạn tin HOT'),
        ),
    ]
