# Generated by Django 4.2.6 on 2025-03-05 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0043_work_hot_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='du_kien_xuat_canh',
            field=models.DateField(blank=True, null=True, verbose_name='Dự kiến xuất cảnh'),
        ),
        migrations.AlterField(
            model_name='work',
            name='han_dang_ky',
            field=models.DateField(blank=True, max_length=250, null=True, verbose_name='Hạn đăng ký'),
        ),
        migrations.AlterField(
            model_name='work',
            name='ngay_thi_tuyen',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày thi tuyển'),
        ),
    ]
