# Generated by Django 4.2.6 on 2025-03-05 14:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0044_alter_work_du_kien_xuat_canh_alter_work_han_dang_ky_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='du_kien_xuat_canh',
            field=models.DateField(choices=[(datetime.date(2025, 3, 1), '03/2025'), (datetime.date(2025, 4, 1), '04/2025'), (datetime.date(2025, 5, 1), '05/2025'), (datetime.date(2025, 6, 1), '06/2025'), (datetime.date(2025, 7, 1), '07/2025'), (datetime.date(2025, 8, 1), '08/2025'), (datetime.date(2025, 9, 1), '09/2025'), (datetime.date(2025, 10, 1), '10/2025'), (datetime.date(2025, 11, 1), '11/2025'), (datetime.date(2025, 12, 1), '12/2025'), (datetime.date(2026, 1, 1), '01/2026'), (datetime.date(2026, 2, 1), '02/2026'), (datetime.date(2026, 3, 1), '03/2026'), (datetime.date(2026, 4, 1), '04/2026'), (datetime.date(2026, 5, 1), '05/2026'), (datetime.date(2026, 6, 1), '06/2026'), (datetime.date(2026, 7, 1), '07/2026'), (datetime.date(2026, 8, 1), '08/2026'), (datetime.date(2026, 9, 1), '09/2026'), (datetime.date(2026, 10, 1), '10/2026'), (datetime.date(2026, 11, 1), '11/2026'), (datetime.date(2026, 12, 1), '12/2026'), (datetime.date(2027, 1, 1), '01/2027'), (datetime.date(2027, 2, 1), '02/2027'), (datetime.date(2027, 3, 1), '03/2027'), (datetime.date(2027, 4, 1), '04/2027'), (datetime.date(2027, 5, 1), '05/2027'), (datetime.date(2027, 6, 1), '06/2027'), (datetime.date(2027, 7, 1), '07/2027'), (datetime.date(2027, 8, 1), '08/2027'), (datetime.date(2027, 9, 1), '09/2027'), (datetime.date(2027, 10, 1), '10/2027'), (datetime.date(2027, 11, 1), '11/2027'), (datetime.date(2027, 12, 1), '12/2027'), (datetime.date(2028, 1, 1), '01/2028'), (datetime.date(2028, 2, 1), '02/2028'), (datetime.date(2028, 3, 1), '03/2028'), (datetime.date(2028, 4, 1), '04/2028'), (datetime.date(2028, 5, 1), '05/2028'), (datetime.date(2028, 6, 1), '06/2028'), (datetime.date(2028, 7, 1), '07/2028'), (datetime.date(2028, 8, 1), '08/2028'), (datetime.date(2028, 9, 1), '09/2028'), (datetime.date(2028, 10, 1), '10/2028'), (datetime.date(2028, 11, 1), '11/2028'), (datetime.date(2028, 12, 1), '12/2028')], default=datetime.date.today, verbose_name='Dự kiến xuất cảnh'),
        ),
    ]
