# Generated by Django 4.2.6 on 2025-03-05 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0048_alter_work_du_kien_xuat_canh'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(default=0, max_length=250, verbose_name='Giá tiền')),
                ('khuyen_mai', models.CharField(blank=True, max_length=250, null=True, verbose_name='Khuyến mại')),
                ('active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=1)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Tiền nạp tài khoản',
                'ordering': ('id',),
            },
        ),
    ]
