# Generated by Django 4.2.6 on 2025-03-07 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0049_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='hot',
        ),
    ]
