# Generated by Django 4.2.6 on 2025-03-01 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ('-id',), 'verbose_name_plural': 'Bài Viết'},
        ),
        migrations.AlterModelOptions(
            name='cate',
            options={'ordering': ('-id',), 'verbose_name_plural': 'Danh mục'},
        ),
    ]
