# Generated by Django 4.2.6 on 2025-03-01 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blog_options_alter_cate_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(blank=True, max_length=127, unique=True),
        ),
        migrations.AlterField(
            model_name='cate',
            name='slug',
            field=models.SlugField(blank=True, max_length=127, unique=True),
        ),
    ]
