# Generated by Django 4.2.6 on 2025-03-03 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_blog_slug_alter_cate_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='user',
        ),
        migrations.RemoveField(
            model_name='cate',
            name='user',
        ),
    ]
