# Generated by Django 4.2.6 on 2025-02-26 07:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('city', '0013_remove_province_country_remove_province_user'),
        ('profession', '0002_profession_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=127, unique=True)),
                ('priority', models.IntegerField(default=1)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('quoc_gia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='province_country', to='city.country', verbose_name='Quốc gia')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provinces', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Tỉnh, khu vực',
                'ordering': ('name',),
            },
        ),
    ]
