# Generated by Django 4.2.6 on 2025-02-26 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0005_alter_work_province'),
        ('profession', '0003_province'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Province',
        ),
    ]
