# Generated by Django 4.2.6 on 2025-03-01 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profession', '0004_delete_province'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profession',
            name='slug',
            field=models.SlugField(blank=True, max_length=127, unique=True),
        ),
    ]
