# Generated by Django 4.2.6 on 2025-03-03 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profession', '0005_alter_profession_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profession',
            name='user',
        ),
    ]
