# Generated by Django 4.2.6 on 2025-02-26 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Admin'), (2, 'Ứng viên'), (3, 'Nhà tuyển dụng')], default=1, verbose_name='Vai trò'),
        ),
    ]
