# Generated by Django 4.2.6 on 2025-02-26 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='chuc_vu',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Chức vụ'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='kinh_nghiem',
            field=models.CharField(default=0, verbose_name='Kinh nghiệm'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='noi_lam_viec',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Nơi làm việc'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='ten_viet_tat',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Tên viết tắt'),
        ),
    ]
