# Generated by Django 4.2.6 on 2025-02-26 13:10

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_customuser_ten_viet_tat'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avata',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='user', verbose_name='Ảnh'),
        ),
    ]
