# Generated by Django 4.2.6 on 2025-02-27 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0020_rename_quoc_gia_province_country'),
        ('user', '0007_remove_customuser_zalo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='tinh_thanh_pho',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='city.city', verbose_name='Tỉnh/ Thành phố'),
        ),
    ]
