# Generated by Django 4.2.6 on 2025-02-28 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_advisory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advisory',
            options={'ordering': ('-id',), 'verbose_name_plural': 'Tư vấn'},
        ),
    ]
