# Generated by Django 4.2.6 on 2025-03-01 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_customuser_otp_code_customuser_otp_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='zalo',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Zalo'),
        ),
    ]
