# Generated by Django 4.2.6 on 2025-03-01 13:11

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_customuser_zalo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='tu_van',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Tư Vấn'),
        ),
    ]
