# Generated by Django 4.2.6 on 2025-03-01 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_customuser_tu_van'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='ten_viet_tat',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Tên viết tắt'),
        ),
    ]
