# Generated by Django 4.2.6 on 2025-03-02 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_customuser_ten_viet_tat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[('admin', 'Admin'), ('applicant', 'Ứng viên'), ('employer', 'Nhà tuyển dụng')], verbose_name='Vai trò'),
        ),
    ]
