# Generated by Django 4.2.6 on 2025-03-02 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('applicant', 'Ứng viên'), ('employer', 'Nhà tuyển dụng')], max_length=20, verbose_name='Vai trò'),
        ),
    ]
