# Generated by Django 4.2.6 on 2025-03-02 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ('-id',), 'verbose_name_plural': 'Người dùng'},
        ),
    ]
