# Generated by Django 4.2.6 on 2025-03-02 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ('id',), 'verbose_name_plural': 'Người dùng'},
        ),
    ]
