# Generated by Django 4.2.6 on 2025-03-03 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_alter_customuser_ngoai_ngu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='sinh_song_tai',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Sinh sống tại'),
        ),
    ]
