# Generated by Django 4.2.6 on 2025-03-04 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_customuser_point_alter_customuser_tot_nghiep'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='free_posts_today',
            field=models.IntegerField(default=2, verbose_name='Đăng miễn phí'),
        ),
    ]
