# Generated by Django 4.2.6 on 2025-03-06 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_customuser_free_posts_today'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_reset_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
