# Generated by Django 4.2.6 on 2025-03-07 03:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_customuser_last_reset_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian xem')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewed_by_employers', to=settings.AUTH_USER_MODEL, verbose_name='Ứng viên')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewed_candidates', to=settings.AUTH_USER_MODEL, verbose_name='Nhà tuyển dụng')),
            ],
            options={
                'verbose_name': 'Lịch sử xem ứng viên',
                'ordering': ['-viewed_at'],
                'unique_together': {('employer', 'candidate')},
            },
        ),
    ]
