# Generated by Django 4.2.6 on 2025-03-07 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0027_candidateview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advisory',
            options={'ordering': ('-id',), 'verbose_name_plural': 'Sđt cần tư vấn'},
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ('id',), 'verbose_name_plural': 'Tài khoản người dùng'},
        ),
    ]
