# Generated by Django 4.2.6 on 2025-03-07 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0028_alter_advisory_options_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ('-id',), 'verbose_name_plural': 'Tài khoản người dùng'},
        ),
    ]
