# Generated by Django 4.2.6 on 2025-03-07 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0029_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gioi_tinh',
            field=models.CharField(blank=True, choices=[('', 'Vui lòng chọn'), ('Nam', 'Nam'), ('Nữ', 'Nữ')], null=True, verbose_name='Giới tính'),
        ),
    ]
