# Generated by Django 4.2.6 on 2025-03-07 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0030_alter_customuser_gioi_tinh'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisory',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Đã thanh toán'),
        ),
    ]
