# Generated by Django 4.2.6 on 2025-03-12 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0031_advisory_is_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='bang_nghe',
            field=models.CharField(blank=True, choices=[('Không', 'Không'), ('Có', 'Có')], max_length=250, null=True, verbose_name='Bằng nghề'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='benh_di_truyen',
            field=models.CharField(blank=True, choices=[('Không', 'Không'), ('Có', 'Có')], max_length=250, null=True, verbose_name='Bệnh di truyền'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='can_nang',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Cân nặng (kg)'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='chieu_cao',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Chiều cao (cm)'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gioi_tinh',
            field=models.CharField(blank=True, choices=[('', 'Vui lòng chọn'), ('Nam', 'Nam'), ('Nữ', 'Nữ')], max_length=250, null=True, verbose_name='Giới tính'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='hinh_xam',
            field=models.CharField(blank=True, choices=[('Không', 'Không'), ('Có', 'Có')], max_length=250, null=True, verbose_name='Hình Xăm'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='hut_thuoc',
            field=models.CharField(blank=True, choices=[('Không', 'Không'), ('Có', 'Có')], max_length=250, null=True, verbose_name='Hút thuốc'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='kinh_nghiem',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Kinh nghiệm'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='nam_sinh',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Năm sinh'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='ngoai_ngu',
            field=models.CharField(blank=True, choices=[('Không', 'Không'), ('Tiếng Nhật', 'Tiếng Nhật'), ('Tiếng Trung', 'Tiếng Trung'), ('Tiếng Anh', 'Tiếng Anh'), ('Tiếng Hàn', 'Tiếng Hàn'), ('Ngoại ngữ khác', 'Ngoại ngữ khác')], max_length=250, null=True, verbose_name='Ngoại ngữ'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='thi_luc',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Thị lực (1 - 10)'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='tot_nghiep',
            field=models.CharField(blank=True, choices=[('Không', 'Không'), ('Tốt nghiệp cấp 2 trở lê', 'Tốt nghiệp cấp 2 trở lên'), ('Tốt nghiệp cấp 3 trở lên', 'Tốt nghiệp cấp 3 trở lên'), ('Bằng nghề trở lên', 'Bằng nghề trở lên'), ('Tốt nghiệp cao đẳng trở lên', 'Tốt nghiệp cao đẳng trở lên'), ('Tốt nghiệp đại học trở lên', 'Tốt nghiệp đại học trở lên')], max_length=250, null=True, verbose_name='Tốt nghiệp'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='uong_ruou',
            field=models.CharField(blank=True, choices=[('Không', 'Không'), ('Có', 'Có')], max_length=250, null=True, verbose_name='Uống rượu'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='viem_gan_b',
            field=models.CharField(blank=True, choices=[('Không', 'Không'), ('Có', 'Có')], max_length=250, null=True, verbose_name='Viêm gan B'),
        ),
    ]
